/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LieuLieuIdRouteImport } from './routes/lieu.$lieuId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LieuLieuIdRoute = LieuLieuIdRouteImport.update({
  id: '/lieu/$lieuId',
  path: '/lieu/$lieuId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lieu/$lieuId': typeof LieuLieuIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lieu/$lieuId': typeof LieuLieuIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lieu/$lieuId': typeof LieuLieuIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lieu/$lieuId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lieu/$lieuId'
  id: '__root__' | '/' | '/lieu/$lieuId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LieuLieuIdRoute: typeof LieuLieuIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lieu/$lieuId': {
      id: '/lieu/$lieuId'
      path: '/lieu/$lieuId'
      fullPath: '/lieu/$lieuId'
      preLoaderRoute: typeof LieuLieuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LieuLieuIdRoute: LieuLieuIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
