/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LieuRouteImport } from './routes/lieu'
import { Route as IndexRouteImport } from './routes/index'

const LieuRoute = LieuRouteImport.update({
  id: '/lieu',
  path: '/lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lieu': typeof LieuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lieu': typeof LieuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lieu': typeof LieuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lieu'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lieu'
  id: '__root__' | '/' | '/lieu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LieuRoute: typeof LieuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lieu': {
      id: '/lieu'
      path: '/lieu'
      fullPath: '/lieu'
      preLoaderRoute: typeof LieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LieuRoute: LieuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
